"use client";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { getLoginError, normalizeLoginUsername } from "@/lib/auth-form";
import { appPath } from "@/lib/paths";

export default function LoginPage() { const router = useRouter(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); setLoading(true); try { const r = await fetch(appPath("/api/admin/login"), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: normalizeLoginUsername(username), password }) }); const data = await r.json().catch(() => null); if (!r.ok) { setError(getLoginError(data)); return; } router.replace("/admin"); } catch { setError(getLoginError(null)); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-blue-50 px-4"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-xl shadow-blue-100"><Image src={appPath("/logo-sekolah.png")} alt="Logo sekolah" width={80} height={80} className="mx-auto mb-5 rounded-2xl object-contain" /><h1 className="text-center text-2xl font-black">Login Admin</h1><p className="mb-7 mt-2 text-center text-sm text-slate-500">Kelola pengumpulan foto siswa</p><div className="space-y-4"><input required value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Username" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full rounded-xl border border-slate-200 px-4 py-3" />{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white hover:bg-blue-700 disabled:cursor-wait disabled:opacity-60">{loading ? "Memeriksa..." : "Masuk"}</button></div></form></main>; }
